### ISSUE TITLE
Redmine 3.0 support

### ISSUE THREAD

**Issue by maxbasmanov** [mateusmedeiros/redmine_revision_diff#4]
I have used this plugin and never thought how much i loved it.
After i migrated to Redmine 3.0 it stopped working and it is total disaster to loose this functionality for me.
Could You please add support for Redmine 3.0?
Many thanks.

**Comment by maxbasmanov** [comment]
a little investigation needed:
1/ i had 0.1.1 installed on R2.6
2/ installed from redmine plugins page 0.1.2 from zip on R3/0 and it did not work
3/ cleared
4/ copied 0.1.1 from R2.6 backup and it worked perfectly

**Comment by mateusmedeiros** [comment]
Thanks for telling me. I'll take a look this weekend.

**Comment by maxbasmanov** [comment]
Hello,

I thought it was very strange and decided to tell You.
Thanks

2015-04-09 5:16 GMT+03:00 Mateus Medeiros notifications@github.com:

**Comment by mateusmedeiros** [comment]
29 days have gone by, sorry about that.

Some complicated stuff happened in my life. But the good (bad) news is that I'll probably be unemployed by the end of the week, so I'll definitely have time to take a look after that. For now, everyone just use the 0.1.1 version since it seems to work and there's almost no difference from version 0.1.2.

**Comment by maxbasmanov** [comment]
Hay, thanks for Your patience :)

Sometimes a decisive step forward is the result of a good kick in the ass ;)

Please remember that being employer is the best way to be unemployed.

Keep cool

2015-05-08 1:51 GMT+03:00 Mateus Medeiros notifications@github.com:

**Comment by mateusmedeiros** [comment]
So, I tested with Redmine 3.0.2 and it worked. What is the exact version you tried? The weird thing is that 0.1.1 works and 0.1.2 don't, because the difference is basically the hardcoded "Changes" that is not hardcoded anymore in 0.1.2. (see 256fc61cff51a67eeea949c114073ca9c4b0c031)

**Comment by maxbasmanov** [comment]
Environment:
  Redmine version                3.0.1.stable.14155
  Ruby version                   2.0.0-p594 (2014-10-27) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem
Redmine plugins:
  redmine_bootstrap_kit          0.2-devel
  redmine_code_review            0.7.0
  redmine_revision_diff          0.1.1

2015-05-08 19:49 GMT+03:00 Mateus Medeiros notifications@github.com:

**Comment by mateusmedeiros** [comment]
@maxbasmanov Holy shit, man! I didn't know I had left you hanging like this. I must have forgot this at the time, really really sorry. 😕 

At the time I made this I was busy as hell, I worked in a full-time job, studied at an university and worked as a freelancer, all at the same time.

This is now pretty much abandoned, I haven't used redmine in a very long time.
Are you still using this plugin? Do you want me to try and investigate the issue more?

**Comment by maxbasmanov** [comment]
Hello :)
Yes, i'm using redmine still but i really do not remember the issue now :)


2017-02-19 2:05 GMT+02:00 Mateus Medeiros <notifications@github.com>:

**Comment by mateusmedeiros** [comment]
@maxbasmanov I certainly don't blame you, haha.
Sorry again, man.

Since you don't even remember the issue, I'm gonna close it, but let me know if anything happens.
